CircuitPython service
adafruit/Bluefruit_LE_Connect_v2 pull request #54
Opened 2022-12-14 18:05 UTC by antonio-openroad

Added support for the Circuit Python service

2022-12-15 18:15 UTC, tannewt requested changes
One minor request. I was able to connect and saw the disconnect you were talking about. Will this show currently connected devices or just newly connected ones? Thanks!

2022-12-20 19:05 UTC, tannewt approved these changes
Thank you!

2023-01-17 15:00 UTC, antonio-openroad commented
> One minor request. I was able to connect and saw the disconnect you were talking about. Will this show currently connected devices or just newly connected ones? Thanks!

I added connected peripherals that support the "FileTransfer service" to the devices list. 

So, if you have a previously bonded a peripheral and it appears as "Connected" on Settings:

![connected](https://user-images.githubusercontent.com/3625420/212931540-0bb6e745-f61e-4b98-af60-190b3025cd37.png)

Then it should appear on the list:
![list](https://user-images.githubusercontent.com/3625420/212931824-b95ee924-47f2-4bb1-ada7-7b40bd23ca42.png)


Is this the behaviour that you expected?

2023-01-17 19:38 UTC, tannewt approved these changes

2023-01-17 19:38 UTC, merged